---
abstract: 'All-in-One Japanese text normalizer'
author:
  - 'pawa <pawapawa@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Fatal: 0
  Test::More: 0.88
  Test::Synopsis::Expectation: 0.02
  Test::Warn: 0.2
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-JA-NormalizeText
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Carp: 0
  Exporter: 0
  HTML::Entities: 3.66
  HTML::Scrubber: 0.1
  Lingua::JA::Dakuon: 0
  Lingua::JA::Moji: 0.3
  Lingua::JA::Regular::Unicode: 0.11
  Sub::Install: 0
  Unicode::Normalize: 1
  perl: 5.8.1
resources:
  bugtracker: https://github.com/pawa-/Lingua-JA-NormalizeText/issues
  license: http://dev.perl.org/licenses
  repository: https://github.com/pawa-/Lingua-JA-NormalizeText
version: 0.30
